### ISSUE TITLE
slide bar is hard to see

### ISSUE THREAD

**Issue by WindSoilder** [hardhackerlabs/theme-vscode#1]
As title, I think the slide bar is really hard to see
![图片](https://github.com/hardhackerlabs/theme-vscode/assets/22256154/1dccb1f4-c655-43ba-9984-82f937945fc7)

Compared to vscode default dark theme:
![图片](https://github.com/hardhackerlabs/theme-vscode/assets/22256154/29d249c5-6d74-4d1e-adff-68dbe56255af)

**Comment by anson0370** [comment]
The scrollbar is indeed a bit unclear, partly because I gave it a high transparency to show the indicator underneath. In my usage scenario, I hardly ever pay attention to the scrollbar and I rarely use it, so I didn't see it as a problem before. Do you need to be able to see this scrollbar clearly?

**Comment by WindSoilder** [comment]
Yeah, I think it's friendly to user who want to use scrollbar.  Because it can help us to navigate code quickly in some scenario

**Comment by anson0370** [comment]
I've just released version 0.2.3, where I've changed the scrollbar color to a more visible one, while maintaining enough transparency to see the indicators behind. You can give it a try.

![CleanShot 2023-09-09 at 16 52 36@2x](https://github.com/hardhackerlabs/theme-vscode/assets/283559/2c1b433f-9d16-4f63-95c3-eb48ba7d6af3)
